#!/bin/bash
#$ -pe smp 1
#$ -l h_vmem=32G
#$ -l h_rt=240:0:0
#$ -cwd
#$ -j y
#$ -m be

module load bismark
module load bowtie2

bismark_genome_preparation --bowtie2 --verbose /data/scratch/bt211057/02_Genome_indexing/
