#!/bin/bash
#$ -o run_bismark_methylation_extractor.stdout
#$ -e run_bismark_methylation_extractor.stderr
#$ -pe smp 1
#$ -l h_vmem=32G
#$ -l h_rt=100:0:0
#$ -cwd
#$ -t 1-122
#$ -tc 10

module load bismark

module load samtools

ls -1 /data/scratch/bt211057/03_Genome_alignment/*_bismark_bt2.sam.gz >list_of_files.txt

INPUT_FILE=$(sed -n "${SGE_TASK_ID}p" list_of_files.txt)

bismark_methylation_extractor -o ./ -s --bedGraph --counts --report $INPUT_FILE
